"""
Plan 05 AC7 (f3): `sign_result.segment.dropped_frames` counts only valid frames dropped because the worker was busy
(slot overwritten) between the first and the last frame of the sign. Error messages (receive side or worker side),
control messages and empty messages are NOT counted. `frame_result.dropped_frames` keeps its meaning.

Fixtures only (tests.test_ws_live_contract / tests.test_harmonized_live): FakePredictor, LoopExtractor, blank PNGs,
landmark frames generated by tests.test_sign_segmenter.
"""
import json
import os
import sys
import unittest
from collections import deque

import numpy as np

PROJECT_ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
if PROJECT_ROOT not in sys.path:
    sys.path.insert(0, PROJECT_ROOT)

import backend.main as api  # noqa: E402
import src.inference.harmonized_live as hl  # noqa: E402
from tests.test_harmonized_live import PRE, FakePredictor  # noqa: E402
from tests.test_ws_live_contract import URL_640, LoopExtractor, _WsCase, data_url, png_bytes, sign_frames  # noqa: E402

BAD_IMAGE = "data:image/png;base64,@@@not-base64@@@"


class TestWsErrorsAreNotDroppedFrames(_WsCase):
    """AC7-a: error / control messages in the middle of a sign do not count as dropped frames."""

    def test_errors_during_recording(self):
        ws, _ = self.connect()
        messages, inserted = [], False
        for _ in range(3 * len(self.t)):
            self.send_frame(ws)
            got = self.until_frame_result(ws)
            messages += got
            self.assertEqual(got[-1]["type"], "frame_result", got[-1])
            if any(m["type"] == "sign_result" for m in got):
                break
            if not inserted and got[-1]["segment"]["state"] == "recording":
                inserted = True
                ws.send_text('{"image": "abc", ')
                self.expect_error(ws, "bad_message")
                ws.send_text(json.dumps({"type": "control", "action": "explode"}))
                self.expect_error(ws, "bad_message")
                self.send_frame(ws, ts=self.ts * 1000.0 / 30.0)          # same timestamp as the last valid frame
                self.expect_error(ws, "bad_timestamp")
                self.send_frame(ws, BAD_IMAGE)                             # new timestamp
                self.expect_error(ws, "decode_failed")
                self.send_frame(ws, data_url(png_bytes(320, 240)))         # new timestamp
                self.expect_error(ws, "frame_too_small")
        self.assertTrue(inserted, "the fixture sign never reached the recording state")
        signs = [m for m in messages if m["type"] == "sign_result"]
        self.assertEqual(len(signs), 1, [m["type"] for m in messages if m["type"] != "frame_result"])
        self.assertEqual(signs[0]["segment"]["dropped_frames"], 0)
        frames = [m for m in messages if m["type"] == "frame_result"]
        self.assertTrue(frames)
        self.assertTrue(all(f["dropped_frames"] == 0 for f in frames), [f["dropped_frames"] for f in frames])


class TestWorkerSeq(unittest.TestCase):
    """AC7-b: the worker passes seq = dropped_frames + frame_seq + 1 to the segmenter."""

    def _run(self, bumps, bad_at):
        """bumps: {frame index: +n dropped before that frame}; bad_at: frame index before which a broken image is
        processed. Returns (events, frame states, seqs passed to session.process, d per valid frame, stats)."""
        t, k, v = sign_frames()
        session = hl.HarmonizedLiveSession(FakePredictor(), dict(PRE), extractor=LoopExtractor(k, v))
        seqs = []
        original = session.process

        def spy(frame_bgr, t_s, seq=None):
            seqs.append(seq)
            return original(frame_bgr, t_s, seq=seq)

        session.process = spy
        stats = {"frame_seq": 0, "last_done": None, "rates": deque(maxlen=30)}
        d, ds, states, events = 0, [], [], []
        for i, x in enumerate(t):
            d += bumps.get(i, 0)
            if i == bad_at:
                before = stats["frame_seq"]
                out = api._process_frame_worker_harmonized(
                    {"image": BAD_IMAGE, "t_s": float(x) - 0.5 / 30.0, "received_seq": 1000 * i + 500,
                     "client_ts": None, "timestamp_source": "server", "dropped_frames": d}, session, stats)
                self.assertEqual([m["type"] for m in out], ["error"])
                self.assertEqual(stats["frame_seq"], before)
            out = api._process_frame_worker_harmonized(
                {"image": URL_640, "t_s": float(x), "received_seq": 1000 * i, "client_ts": None,
                 "timestamp_source": "server", "dropped_frames": d}, session, stats)
            ds.append(d)
            states.append(out[-1]["segment"]["state"])
            events += [m for m in out if m["type"] != "frame_result"]
        return events, states, seqs, ds, stats

    def _check_seqs(self, seqs, ds):
        self.assertEqual(len(seqs), len(ds))
        for kk in range(len(seqs) - 1):
            self.assertGreater(seqs[kk + 1], seqs[kk])
            self.assertEqual(seqs[kk + 1] - seqs[kk] - 1, ds[kk + 1] - ds[kk], kk)

    def test_drops_inside_recording(self):
        t, _, _ = sign_frames()
        i2, i1, bad = (int(np.searchsorted(t, s)) for s in (1.5, 1.9, 1.7))
        events, states, seqs, ds, stats = self._run({i2: 2, i1: 1}, bad)
        for i in (i2, i1, bad):
            self.assertEqual(states[i], "recording", i)
        signs = [e for e in events if e["type"] == "sign_result"]
        self.assertEqual(len(signs), 1, [e["type"] for e in events])
        self.assertEqual(signs[0]["segment"]["dropped_frames"], 3)
        self._check_seqs(seqs, ds)
        self.assertEqual(stats["frame_seq"], len(t))

    def test_drops_in_idle_before_sign(self):
        t, _, _ = sign_frames()
        i2, i1 = (int(np.searchsorted(t, s)) for s in (0.1, 0.2))
        events, states, seqs, ds, stats = self._run({i2: 2, i1: 1}, None)
        for i in (i2, i1):
            self.assertEqual(states[i], "idle", i)
        signs = [e for e in events if e["type"] == "sign_result"]
        self.assertEqual(len(signs), 1, [e["type"] for e in events])
        self.assertEqual(signs[0]["segment"]["dropped_frames"], 0)
        self._check_seqs(seqs, ds)


if __name__ == "__main__":
    unittest.main()
