"""
Level 2 report generated only from files: <run>/test_logits.npz, <run>/metrics.json, the unified manifest,
optionally more seed runs and the old-vs-new comparison JSON (scripts/compare_isolated_models.py).

Groups (test rows):
  vslgh_unseen_signer : VSL-GH segments of signer S06 (never in train/val)
  qipedc_only_class   : QIPEDC rows whose class has no VSL-GH training sample; only classes with
                        >= 2 distinct QIPEDC recordings (one of them unseen in training) are counted
  total               : every test row
Top-1 / Top-5 with Wilson 95% CI and a class-cluster bootstrap 95% CI (1000 resamples of classes).
Usage: python scripts/report_unified.py --run <dir> [--extra-runs <dir> ...] [--compare <json>] --out <md>
"""
import argparse
import json
import os

import numpy as np
import pandas as pd


def wilson(k, n, z=1.96):
    p = k / n
    c = (p + z * z / (2 * n)) / (1 + z * z / n)
    h = z * np.sqrt(p * (1 - p) / n + z * z / (4 * n * n)) / (1 + z * z / n)
    return 100 * (c - h), 100 * (c + h)


def cluster_boot(hits, classes, n_boot=1000, seed=0):
    rng = np.random.default_rng(seed)
    uniq = np.unique(classes)
    by = {c: hits[classes == c] for c in uniq}
    stats = []
    for _ in range(n_boot):
        pick = rng.choice(uniq, len(uniq), replace=True)
        v = np.concatenate([by[c] for c in pick])
        stats.append(v.mean() * 100)
    return np.percentile(stats, 2.5), np.percentile(stats, 97.5)


def group_rows(test, train):
    vslgh_classes = set(train.loc[train.source == "vslgh", "gloss_normalized"])
    allq = pd.concat([train, test])
    allq = allq[allq.source == "qipedc"]
    recs = allq.groupby("gloss_normalized").recording_group.nunique()
    q_only = (test.source == "qipedc") & ~test.gloss_normalized.isin(vslgh_classes)
    enough = test.gloss_normalized.map(recs).fillna(0) >= 2
    return {"vslgh_unseen_signer": (test.source == "vslgh").values,
            "qipedc_only_class": (q_only & enough).values,
            "total": np.ones(len(test), bool)}, int((q_only & ~enough).sum())


def evaluate(run, test, masks, classes_txt):
    d = np.load(os.path.join(run, "test_logits.npz"))
    order = {v: i for i, v in enumerate(d["video_ids"])}
    idx = np.array([order[v] for v in test.video_id])  # align logits with manifest rows
    logits, labels = d["logits"].astype(np.float32)[idx], d["labels"][idx]
    assert all(classes_txt[l] == g for l, g in zip(labels, test.gloss_normalized)), "label order mismatch"
    top1 = (logits.argmax(1) == labels).astype(float)
    top5 = np.array([l in r for l, r in zip(labels, np.argsort(-logits, 1)[:, :5])], float)
    out = {}
    for g, m in masks.items():
        n, cls = int(m.sum()), test.gloss_normalized.values[m]
        out[g] = {"n": n, "classes": int(len(set(cls)))}
        for k, v in (("top1", top1[m]), ("top5", top5[m])):
            out[g][k] = 100 * v.mean()
            out[g][k + "_wilson"] = wilson(int(v.sum()), n)
            out[g][k + "_cluster"] = cluster_boot(v, cls)
    return out


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--run", required=True)
    ap.add_argument("--extra-runs", nargs="*", default=[])
    ap.add_argument("--manifest-dir", default="data/splits/unified")
    ap.add_argument("--compare")
    ap.add_argument("--out", required=True)
    args = ap.parse_args()
    test = pd.read_csv(os.path.join(args.manifest_dir, "test.csv"))
    train = pd.read_csv(os.path.join(args.manifest_dir, "train.csv"))
    classes = [l.strip() for l in open(os.path.join(args.manifest_dir, "classes.txt"), encoding="utf-8") if l.strip()]
    masks, dropped = group_rows(test, train)
    main_res = evaluate(args.run, test, masks, classes)
    metrics = json.load(open(os.path.join(args.run, "metrics.json"), encoding="utf-8"))

    f = lambda a, b: f"[{a:.1f}, {b:.1f}]"
    out = ["# Level 2 — unified isolated-sign model (generated by scripts/report_unified.py)", "",
           f"Run: `{args.run}` (seed 42, pre-declared primary). Classes {len(classes)}; "
           f"model selected on VAL (epoch {metrics['val_best']['epoch']}, val top-1 {metrics['val_best']['top1']:.1f}); TEST evaluated once.",
           f"Split integrity: {metrics.get('split_integrity', {}).get('status', 'n/a')}.", "",
           "| Group | Test rows | Classes | Top-1 | Wilson 95% | class-bootstrap 95% | Top-5 | Wilson 95% |",
           "|---|---|---|---|---|---|---|---|"]
    names = {"vslgh_unseen_signer": "VSL-GH words, unseen signer S06",
             "qipedc_only_class": "QIPEDC-only words (≥2 recordings), unseen recording", "total": "Total"}
    for g, r in main_res.items():
        out.append(f"| {names[g]} | {r['n']} | {r['classes']} | **{r['top1']:.1f}** | {f(*r['top1_wilson'])} | "
                   f"{f(*r['top1_cluster'])} | {r['top5']:.1f} | {f(*r['top5_wilson'])} |")
    out.append(f"\nQIPEDC-only test rows excluded for < 2 recordings: {dropped}.")
    if args.extra_runs:
        out += ["", "## Seed variance (not used for selection)", "", "| Run | " + " | ".join(names[g] for g in masks) + " |",
                "|---" * (len(masks) + 1) + "|"]
        for run in [args.run] + args.extra_runs:
            r = main_res if run == args.run else evaluate(run, test, masks, classes)
            out.append(f"| `{os.path.basename(run.rstrip('/'))}` | " + " | ".join(f"{r[g]['top1']:.1f}" for g in masks) + " |")
    if args.compare and os.path.exists(args.compare):
        c = json.load(open(args.compare, encoding="utf-8"))
        out += ["", "## Gate (Việc 3): old backend model vs new, clips neither model has seen", "",
                f"Label spaces: old {c['label_spaces']['old']}, new {c['label_spaces']['new']}, shared {c['label_spaces']['both']}. "
                f"Missing npz: {c['missing_npz']}.", ""]
        if "sanity_new_full_test" in c:
            out.append(f"Sanity (new model through the comparison path, full test): {c['sanity_new_full_test']}.\n")
        out += ["| Set | n | Old top-1 [95%] | New top-1 [95%] | Old top-5 | New top-5 | McNemar p (old-only / new-only) |",
                "|---|---|---|---|---|---|---|"]
        for s, e in c["sets"].items():
            o, n, m = e["old"], e["new"], e["mcnemar_top1"]
            if not o["n"]:
                continue
            out.append(f"| {s} | {o['n']} | {o['top1']:.1f} {o['top1_ci']} | {n['top1']:.1f} {n['top1_ci']} | "
                       f"{o['top5']:.1f} | {n['top5']:.1f} | {m['p']:.3g} ({m['old_only']} / {m['new_only']}) |")
        hc = c["sets"].get("hcmue_fair", {}).get("by_region_not_signer")
        if hc:
            out += ["", "HCMUE by page region (no signer IDs exist in the source):", "",
                    "| Region | n | Old top-1 | New top-1 |", "|---|---|---|---|"]
            out += [f"| {k} | {v['n']} | {v['old_top1']:.1f} | {v['new_top1']:.1f} |" for k, v in hc.items()]
        if "hcmue_new_all_known_labels" in c:
            h = c["hcmue_new_all_known_labels"]
            out.append(f"\nNew model on all HCMUE clips with a label in its 876 classes: n={h['n']}, "
                       f"top-1 {h['top1']:.1f} {h['top1_ci']}, top-5 {h['top5']:.1f}.")
    with open(args.out, "w", encoding="utf-8") as fh:
        fh.write("\n".join(out) + "\n")
    json.dump({"primary": main_res}, open(os.path.splitext(args.out)[0] + ".json", "w", encoding="utf-8"), indent=2,
              ensure_ascii=False, default=float)
    print("\n".join(out))


if __name__ == "__main__":
    main()
