"""
Markdown report for Level 1 nested LOSO, generated only from JSON/CSV outputs:
  <run>/nested_report.json, <run>/nested_predictions.csv (scripts/train_alphabet_nested.py)
  signer diagnostics JSON (scripts/analyze_alphabet_signers.py), aggregate fields only
Usage: python scripts/report_alphabet_nested.py --primary <dir> [--variants <dir>] [--diagnostics <json>] --out <md>
"""
import argparse
import csv
import json
import os
from collections import defaultdict

TONE_PREFIX = "dấu"


def fmt_ci(s):
    return f"{s['mean']:.1f} [{s['ci95'][0]:.1f}, {s['ci95'][1]:.1f}]"


def fold_table(run):
    lines = ["| Test signer | Selected (inner val) | Overall | Letters | Tone marks |", "|---|---|---|---|---|"]
    for f in run["folds"]:
        sel = f["selected"]
        key = f"{sel['model']}|{sel['epochs']}|{sel['variant']}"
        lines.append(f"| {f['test_signer'].replace('hauuto_', '')} | {sel['model']} {sel['epochs']} ep {sel['variant']} "
                     f"({f['inner_val_top1'][key]:.1f}) | {f['overall']['top1']:.1f} | {f['letters']['top1']:.1f} "
                     f"(n={f['letters']['n']}) | {f['tones']['top1']:.1f} (n={f['tones']['n']}) |")
    s = run["summary"]
    lines.append(f"| **Mean [95% t-CI, 4 folds]** | | **{fmt_ci(s['overall'])}** | **{fmt_ci(s['letters'])}** | **{fmt_ci(s['tones'])}** |")
    return lines


def session_split(pred_csv, run, signer):
    acc = defaultdict(lambda: [0, 0])
    with open(pred_csv, encoding="utf-8") as f:
        for r in csv.DictReader(f):
            if r["run"] != run or r["test_signer"] != signer:
                continue
            sess = r["sample_id"].split("_")[-2]
            part = "tones" if r["true"].startswith(TONE_PREFIX) else "letters"
            for k in (sess, f"{sess}/{part}"):
                acc[k][0] += r["true"] == r["pred"]
                acc[k][1] += 1
    return {k: (100 * c / n, n) for k, (c, n) in sorted(acc.items())}


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--primary", required=True)
    ap.add_argument("--variants")
    ap.add_argument("--diagnostics")
    ap.add_argument("--out", required=True)
    args = ap.parse_args()
    P = json.load(open(os.path.join(args.primary, "nested_report.json"), encoding="utf-8"))
    out = ["# Level 1 — nested leave-one-signer-out (generated by scripts/report_alphabet_nested.py)", "",
           f"Data: hauuto, {P['clips']['hauuto']} clips, 4 signers, 34 classes (29 letters + 5 tone marks); "
           f"external QIPEDC letters {P['clips']['qipedc']} clips. Licence unknown, internal use only.",
           f"Protocol: {P['protocol']}. Candidates: MLP / BiGRU x epochs {P['epochs_grid']}; seed {P['seed']}.", "",
           "## Primary (features as deployed: resample by frame index)", ""]
    out += fold_table(P["runs"]["frame"])
    e = P["external"]
    out += ["", f"External QIPEDC letters (model selected by LOSO over all 4 signers: {' '.join(map(str, e['selected']))}, "
                f"trained on all 4): {e['overall']['top1']:.1f}% on {e['overall']['n']} clips; "
                f"**{e['per_recording']['top1']:.1f}% on {e['per_recording']['n']} distinct recordings, "
                f"Wilson 95% [{e['per_recording']['wilson95'][0]:.1f}, {e['per_recording']['wilson95'][1]:.1f}]**.", ""]

    pred = os.path.join(args.primary, "nested_predictions.csv")
    tai = session_split(pred, "frame", "hauuto_tai")
    out += ["### Signer tai by recording session (primary run)", "", "| Session | Clips | Top-1 |", "|---|---|---|"]
    out += [f"| {k} | {n} | {a:.1f} |" for k, (a, n) in tai.items()]

    if args.diagnostics:
        D = json.load(open(args.diagnostics, encoding="utf-8"))
        keys = [("duration_s", "clip s"), ("fps_pts", "fps (PTS)"), ("dt_cv", "frame-interval CV"),
                ("detection_rate", "hand detected"), ("roll_deg", "hand roll deg"), ("hand_size", "hand size"),
                ("palm_facing_deg", "palm vs camera deg")]
        out += ["", "## Capture diagnostics per signer (median [p10, p90])", "",
                "| Signer | mirrored | " + " | ".join(k[1] for k in keys) + " | tone wrist travel (palms) |",
                "|---" * (len(keys) + 3) + "|"]
        for s, r in D.items():
            if s.startswith("_"):
                continue
            cells = [f"{r[k]['median']:.2f} [{r[k]['p10']:.2f}, {r[k]['p90']:.2f}]" if k in r else "-" for k, _ in keys]
            out.append(f"| {s.replace('hauuto_', '')} | {100 * r['mirrored_frac']:.0f}% | " + " | ".join(cells)
                       + f" | {r.get('tone_wrist_travel_palms_median', float('nan')):.2f} |")

    if args.variants and os.path.exists(os.path.join(args.variants, "nested_report.json")):
        V = json.load(open(os.path.join(args.variants, "nested_report.json"), encoding="utf-8"))
        out += ["", "## Exploratory feature variants (each fully nested; not deployed)", "",
                "| Run | Overall | Letters | Tone marks | tai tones |", "|---|---|---|---|---|"]
        for name, run in V["runs"].items():
            s = run["summary"]
            tai_t = next(f["tones"]["top1"] for f in run["folds"] if f["test_signer"] == "hauuto_tai")
            out.append(f"| {name} | {fmt_ci(s['overall'])} | {fmt_ci(s['letters'])} | {fmt_ci(s['tones'])} | {tai_t:.1f} |")
        ve = V["external"]
        out += ["", f"variant_selected = variant chosen inside the inner loop (unbiased for the whole procedure). "
                    f"External (LOSO-4 selected {' '.join(map(str, ve['selected']))}): "
                    f"{ve['per_recording']['top1']:.1f}% on {ve['per_recording']['n']} recordings "
                    f"[{ve['per_recording']['wilson95'][0]:.1f}, {ve['per_recording']['wilson95'][1]:.1f}]."]
    with open(args.out, "w", encoding="utf-8") as f:
        f.write("\n".join(out) + "\n")
    print("\n".join(out))


if __name__ == "__main__":
    main()
