"""
Step 4a-4c report, generated only from files (run dirs with metrics.json + test_logits.npz + checkpoint label_map,
and the 4a/4b source-classifier JSONs). Rules: reports/step4_2026-09-26/PREREGISTRATION.md.

Usage: python scripts/report_step4.py --baseline reports/unified_run_2026-09-25/run \
         --runs H-keepz=<dir> H-dropz=<dir> [--run-360 H-keepz-360=<dir>] \
         [--aux-runs H-keepz-seed43=<dir> H-keepz-notrim=<dir>] [--dict-run <dir>] [--dict-run-360 <dir>] \
         --out reports/step4_2026-09-26/REPORT.md

Selection (pre-registered, VAL only): z variant among --runs (< 0.5 point -> drop hand z); then --run-360 replaces
it only if >= 0.5 point better. --aux-runs are reported but never selected (seed variance, trimming ablation).
"""
import argparse
import json
import os
import subprocess
import sys

import numpy as np
import pandas as pd

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
sys.path.insert(0, os.path.join(ROOT, "scripts"))
os.chdir(ROOT)
from report_unified import group_rows, wilson  # noqa: E402

DIFFERENT_SIGN = {"xem", "kết quả", "yếu", "thường xuyên"}


def run_classes(run):
    import torch
    ck = torch.load(os.path.join(run, "stgcn_unified_best.pt"), map_location="cpu", weights_only=False)
    lm = ck["label_map"]
    return [c for c, _ in sorted(lm.items(), key=lambda kv: kv[1])]


def load_run(run, test):
    d = np.load(os.path.join(run, "test_logits.npz"))
    order = {v: i for i, v in enumerate(d["video_ids"])}
    rows = test[test.video_id.isin(order)].copy()
    idx = np.array([order[v] for v in rows.video_id])
    classes = run_classes(run)
    logits = d["logits"].astype(np.float32)[idx]
    assert all(classes[l] == g for l, g in zip(d["labels"][idx], rows.gloss_normalized)), f"label order {run}"
    rank = np.argsort(-logits, 1)
    true = np.array([classes.index(g) for g in rows.gloss_normalized])
    hit = {k: np.array([t in r[:k] for t, r in zip(true, rank)], float) for k in (1, 5, 10)}
    pred = [classes[r[0]] for r in rank]
    return rows.reset_index(drop=True), hit, pred


def summ(v):
    n = len(v)
    if n == 0:
        return "n=0"
    s = f"{100 * v.mean():.1f} [{wilson(int(v.sum()), n)[0]:.1f}, {wilson(int(v.sum()), n)[1]:.1f}]"
    return s


def git_head():
    return subprocess.run(["git", "rev-parse", "--short", "HEAD"], capture_output=True, text=True).stdout.strip()


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--baseline", required=True)
    ap.add_argument("--runs", nargs="+", required=True, help="NAME=DIR, native-resolution z variants (candidates)")
    ap.add_argument("--run-360", help="NAME=DIR, chosen z variant at 360 px (candidate vs the native choice)")
    ap.add_argument("--aux-runs", nargs="*", default=[], help="NAME=DIR, reported only, never selected")
    ap.add_argument("--dict-run", help="dictionary-word model, native resolution")
    ap.add_argument("--dict-run-360", help="dictionary-word model, 360 px (reported as 4c only if 360 is chosen)")
    ap.add_argument("--out", required=True)
    args = ap.parse_args()
    test = pd.read_csv("data/splits/unified/test.csv")
    train = pd.read_csv("data/splits/unified/train.csv")
    man = pd.concat([train, pd.read_csv("data/splits/unified/val.csv"), test])
    shared = {c for c, s in man.groupby("gloss_normalized").source.apply(set).items() if {"vslgh", "qipedc"} <= s}
    masks_all, _ = group_rows(test, train)
    native = dict(r.split("=", 1) for r in args.runs)
    r360 = dict([args.run_360.split("=", 1)]) if args.run_360 else {}
    aux = dict(r.split("=", 1) for r in args.aux_runs)
    runs = {"baseline (legacy input)": args.baseline, **native, **r360, **aux}

    out = [f"# Step 4a–4c report (generated by scripts/report_step4.py @ {git_head()})", "",
           "Rules fixed in advance: `PREREGISTRATION.md`. TEST evaluated once per trained model; no TTA.", ""]

    # 4a
    a = json.load(open("reports/step4_2026-09-26/4a/shortcut_85.json", encoding="utf-8"))
    b = a["balanced"]
    out += ["## 4a — shortcut test on the classes present in both sources", "",
            f"Shared classes: {a['shared_classes']}; balanced {b['n_by_source']} (one clip per QIPEDC recording, "
            "as many VSL-GH segments from different sentence recordings); chance 50%.", "",
            "| Features | Source classifier (balanced acc.) |", "|---|---|", f"| all | **{b['all']}** |"]
    out += [f"| {k} only | {v} |" for k, v in b["single_group"].items()]
    c = a["cross_source_current_model"]
    out += ["", f"→ With the same words on both sides the source is still identified ({b['all']}%): the shortcut is real, "
                "not a vocabulary artefact.", "",
            f"Current model, cross-source, {c['classes_kept']} shared classes (excluded as signed differently: "
            f"{', '.join(c['excluded_different_sign'])}): QIPEDC unseen clips top-1 {c['qipedc_test_only']['top1']}% "
            f"{c['qipedc_test_only']['top1_ci']} (n={c['qipedc_test_only']['n']}), top-5 {c['qipedc_test_only']['top5']}%; "
            f"S06 same classes {c['s06_reference']['top1']}% (n={c['s06_reference']['n']}).", ""]

    # 4b
    out += ["## 4b — harmonised input, retrained", "",
            "### Selection on VAL (pre-registered: mean of VSL-GH and QIPEDC VAL top-1)", "",
            "| Run | VAL VSL-GH (S05) | VAL QIPEDC | Balanced VAL | best epoch |", "|---|---|---|---|---|"]
    bal = {}
    for name, run in runs.items():
        m = json.load(open(os.path.join(run, "metrics.json"), encoding="utf-8"))
        vb = m.get("val_by_source")
        if vb:
            bal[name] = (vb["vslgh"]["top1"] + vb["qipedc"]["top1"]) / 2
            tag = " (not a candidate)" if name in aux else ""
            out.append(f"| {name}{tag} | {vb['vslgh']['top1']:.1f} | {vb['qipedc']['top1']:.1f} | **{bal[name]:.1f}** | {m['val_best']['epoch']} |")
        else:
            out.append(f"| {name} | n/a (run predates val_by_source) | | | {m['val_best']['epoch']} |")
    chosen = None
    cand = {k: bal[k] for k in native if k in bal}
    if cand:
        # pre-registered: z variant first; < 0.5 point -> the simpler one (drop hand z)
        best = max(cand, key=cand.get)
        simple = [k for k in cand if "dropz" in k]
        chosen = simple[0] if simple and best != simple[0] and cand[best] - cand[simple[0]] < 0.5 else best
        out.append(f"\nz variant by the rule (native resolution): **{chosen}**.")
        for k in r360:
            if k in bal:
                d = bal[k] - bal[chosen]
                verdict = "adopted" if d >= 0.5 else "not adopted (native resolution kept)"
                out.append(f"360 px: {k} vs {chosen}: {d:+.1f} points balanced VAL → {verdict}.")
                if d >= 0.5:
                    chosen = k
        out.append(f"\nChosen by the rule: **{chosen}**.")
    notrim = [k for k in aux if "notrim" in k and k in bal]
    keep_native = next((k for k in native if "keepz" in k and k in bal), None)
    for k in notrim:
        if keep_native:
            d = bal[keep_native] - bal[k]
            verdict = "trimming credited" if d >= 0.5 else "trimming NOT credited (< 0.5 point)"
            out.append(f"Trimming ablation: {keep_native} (trimmed) vs {k}: {d:+.1f} points balanced VAL → {verdict}.")

    out += ["", "### TEST — three groups (top-1 [Wilson 95%]; top-5)", "",
            "| Run | S06 unseen signer | QIPEDC-only words | Total | Cross-source (shared classes − 4 words) |",
            "|---|---|---|---|---|"]
    results = {}
    for name, run in runs.items():
        rows, hit, pred = load_run(run, test)
        mk = {g: m[test.video_id.isin(rows.video_id).values] for g, m in masks_all.items()}
        cross = ((rows.source == "qipedc") & rows.gloss_normalized.isin(shared - DIFFERENT_SIGN)).values
        cells = [f"{summ(hit[1][mk[g]])}; {100 * hit[5][mk[g]].mean():.1f}" for g in ("vslgh_unseen_signer", "qipedc_only_class", "total")]
        cells.append(f"{summ(hit[1][cross])}; {100 * hit[5][cross].mean():.1f} (n={int(cross.sum())})")
        tag = " (not a candidate)" if name in aux else ""
        out.append(f"| {name}{tag} | " + " | ".join(cells) + " |")
        results[name] = (rows, hit, pred)

    hz = [f for f in sorted(os.listdir("reports/step4_2026-09-26/4b")) if f.startswith("shortcut_85_harmonized")]
    if hz:
        out += ["", "### Source classifier on the harmonised input (4a balanced set)", "",
                "| Variant | all | " + " | ".join(json.load(open(f"reports/step4_2026-09-26/4b/{hz[0]}", encoding='utf-8'))["balanced"]["single_group"]) + " |",
                "|---" * (2 + len(json.load(open(f"reports/step4_2026-09-26/4b/{hz[0]}", encoding='utf-8'))["balanced"]["single_group"])) + "|"]
        for f in hz:
            j = json.load(open(f"reports/step4_2026-09-26/4b/{f}", encoding="utf-8"))
            out.append(f"| hand z {j['hand_z']}, {j['qipedc_kps_dir']} | {j['balanced']['all']} | " +
                       " | ".join(str(v) for v in j["balanced"]["single_group"].values()) + " |")

    # 4c
    dict_run = args.dict_run_360 if chosen in r360 else args.dict_run
    if dict_run and chosen:
        res = "360 px" if chosen in r360 else "native resolution"
        out += ["", f"## 4c — dictionary-word model (QIPEDC only, {res}) vs chosen unified model, same QIPEDC TEST clips", ""]
        d_rows, d_hit, d_pred = load_run(dict_run, test)
        u_rows, u_hit, u_pred = results[chosen]
        common = sorted(set(d_rows.video_id) & set(u_rows[u_rows.source == "qipedc"].video_id))
        di = d_rows.set_index("video_id").index.get_indexer(common)
        ui = u_rows.set_index("video_id").index.get_indexer(common)
        out += [f"Clips: {len(common)} (QIPEDC TEST rows whose class is in both label spaces).", "",
                "| Model | Top-1 | Top-5 | Top-10 |", "|---|---|---|---|"]
        for name, hit, ix in (("dictionary-word (QIPEDC only)", d_hit, di), (f"unified {chosen}", u_hit, ui)):
            out.append(f"| {name} | " + " | ".join(summ(hit[k][ix]) for k in (1, 5, 10)) + " |")
        from scipy.stats import binomtest
        a1, b1 = d_hit[1][di], u_hit[1][ui]
        n01, n10 = int(((a1 == 0) & (b1 == 1)).sum()), int(((a1 == 1) & (b1 == 0)).sum())
        p = binomtest(n10, n01 + n10, 0.5).pvalue if n01 + n10 else 1.0
        out.append(f"\nExact McNemar on top-1: dictionary-only right & unified wrong {n10}, the reverse {n01}, p = {p:.3g}.")
    with open(args.out, "w", encoding="utf-8") as f:
        f.write("\n".join(out) + "\n")
    print("\n".join(out))


if __name__ == "__main__":
    main()
